name: Release creation [Minor]

on:
  workflow_dispatch:

jobs:
  validate-tag-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        id: validate
        shell: bash
        run: |
          echo "Validating tag: ${{ github.ref_name }}"
          
          # Check if the tag is in the format vX.Y.Z-beta.N
          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$ ]]; then
            echo "Error: Tag does not match the format vX.Y.Z-beta.N"
            echo "Example: v1.1.0-beta.1"
            exit 1
          fi
          
          echo "Tag validation successful"

  create-tag-minor:
    name: Create Tag Minor
    runs-on: ubuntu-latest
    needs: validate-tag-beta
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create tag minor
        run: |
          ./scripts/semtag.sh final -s minor 
